In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [2]:
vec = (2 * np.ones(20)) ** np.arange(1, 21) / np.arange(1, 21)
print(vec)

[  2.00000000e+00   2.00000000e+00   2.66666667e+00   4.00000000e+00
   6.40000000e+00   1.06666667e+01   1.82857143e+01   3.20000000e+01
   5.68888889e+01   1.02400000e+02   1.86181818e+02   3.41333333e+02
   6.30153846e+02   1.17028571e+03   2.18453333e+03   4.09600000e+03
   7.71011765e+03   1.45635556e+04   2.75941053e+04   5.24288000e+04]


**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [3]:
s = np.sum(np.fromfunction(lambda i: 0.1 ** (3 * i) * 0.2 ** (4 * i), (6, )))
print(s)

1.0000016


**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [4]:
mat = np.zeros((8, 8))
mat[1::2, ::2] = 1
mat[::2, 1::2] = 1
print(mat)

[[ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]]


**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [5]:
X = np.random.random((5, 2))
x, y = X[:, 0], X[:, 1]
r = np.sqrt(x ** 2 + y ** 2)
phi = np.arctan2(y, x)
print(r, phi)

[ 1.0782637   0.45989518  0.63532316  0.78932085  0.32571706] [ 0.42684345  1.5426385   0.46840834  1.25660091  0.09791533]


**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [6]:
X = np.random.random((10, 10))
ind = np.unravel_index(np.argmax(X, axis=None), X.shape)
ind

(1, 7)

**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [7]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))
x1, x2 = X[:, 0], X[:, 1]
y1, y2 = y[:, 0][0], y[:, 1][0]
m = np.amin(np.sqrt((x1 - y1) ** 2 + (x2 - y2) ** 2))
print(m)

0.0899311408662


**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [8]:
def f(x):
    if x < 0:
        return x ** 2 + 2 * x + 6
    elif 0 <= x <= 2:
        return x + 6
    elif x >= 2:
        return x ** 2 + 4 * x - 4

vec_f = np.vectorize(f)
res = vec_f(np.linspace(-3, 3))
print(res)

[  9.           8.52519783   8.08038317   7.66555602   7.28071637
   6.92586422   6.60099958   6.30612245   6.04123282   5.8063307
   5.60141608   5.42648896   5.28154935   5.16659725   5.08163265
   5.02665556   5.00166597   5.00666389   5.04164931   5.10662224
   5.20158267   5.32653061   5.48146606   5.666389     5.88129946
   6.06122449   6.18367347   6.30612245   6.42857143   6.55102041
   6.67346939   6.79591837   6.91836735   7.04081633   7.16326531
   7.28571429   7.40816327   7.53061224   7.65306122   7.7755102
   7.89795918   8.1636818    9.16326531  10.19283632  11.25239484
  12.34194086  13.46147439  14.61099542  15.79050396  17.        ]


**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [9]:
X = np.random.random((10, 10))
X - np.mean(X, axis=1, keepdims=True)

array([[ -1.38621483e-01,  -1.82282872e-01,   1.33932462e-01,
          3.29822835e-01,   2.85125616e-01,   1.45511191e-01,
         -2.29698251e-01,  -2.73246135e-01,   3.02090038e-01,
         -3.72633401e-01],
       [ -4.70077877e-02,   1.26509728e-01,   1.78906044e-01,
         -2.72376629e-01,  -2.53608209e-01,  -2.14553370e-01,
         -2.81301488e-01,   7.72821296e-02,   3.00769867e-01,
          3.85379715e-01],
       [ -2.67993886e-01,   2.46302679e-01,   1.93855659e-01,
          3.31612746e-01,   4.12014497e-01,  -3.44996216e-01,
          4.24908652e-01,  -3.81706306e-01,  -3.87403325e-01,
         -2.26594498e-01],
       [ -2.79888646e-01,  -3.39659415e-01,   5.33561904e-01,
         -7.73931224e-02,   4.79376354e-01,   4.04431752e-01,
         -3.33213703e-01,  -1.21670269e-01,  -1.94755283e-01,
         -7.07895727e-02],
       [ -3.01824775e-01,  -3.79263305e-01,   3.82948299e-01,
         -3.14494207e-02,  -1.61612706e-01,   4.06327976e-01,
         -4.39602737e-01

**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [10]:
X = np.random.normal(loc=5, scale=2., size=1000)
m = np.mean(X)
d = np.mean((X - m) ** 2)
print(m, d)

5.09812595679 3.91987998901


**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [11]:
np.fromfunction(lambda i, j: (i + j) % 5, (5, 5))


array([[ 0.,  1.,  2.,  3.,  4.],
       [ 1.,  2.,  3.,  4.,  0.],
       [ 2.,  3.,  4.,  0.,  1.],
       [ 3.,  4.,  0.,  1.,  2.],
       [ 4.,  0.,  1.,  2.,  3.]])